SELECT
    D.DEPARTMENT_NAME,
    J.JOB_ID,
    AVG(E.SALARY),
    MAX(E.SALARY),
    MIN(E.SALARY)
FROM HR.EMPLOYEES E
LEFT JOIN HR.DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
LEFT JOIN HR.JOBS J
ON E.JOB_ID = J.JOB_ID
WHERE D.DEPARTMENT_NAME IS NOT NULL
GROUP BY D.DEPARTMENT_NAME, J.JOB_ID
ORDER BY D.DEPARTMENT_NAME, J.JOB_ID
