SELECT
    round(AVG(E.SALARY),2) MEDIA_SALARIAL,
    MAX(E.SALARY) MAXIMO_SALARIO,
    MIN(E.SALARY) MINIMO_SALARIO,
    COUNT(E.EMPLOYEE_ID) QTD_FUNCIONARIO,
    R.REGION_NAME,
    L.CITY
FROM HR.EMPLOYEES E
LEFT JOIN HR.DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID

LEFT JOIN HR.LOCATIONS L
ON D.LOCATION_ID = L.LOCATION_ID

LEFT JOIN HR.COUNTRIES C
ON L.COUNTRY_ID = C.COUNTRY_ID

LEFT JOIN HR.REGIONS R
ON C.REGION_ID = R.REGION_ID
WHERE E.EMPLOYEE_ID IS NOT NULL
GROUP BY R.REGION_NAME, L.CITY
ORDER BY R.REGION_NAME, L.CITY